12:
	g++ twelveone.cpp -std=c++11 -o twelveone
14:
	g++ fourteenone.cpp -std=c++11 -o fourteenone
15:
	g++ fifteenone.cpp -std=c++11 -o fifteenone
clean:
	rm -f twelveone
	rm -f fourteenone
	rm -f fifteenone
	rm -f core.*
	rm -f vgcore.*