default:
	g++ twentyfive.cpp -O3 -std=c++11 -l sqlite3 -o twentyfive
	g++ twentyseven.cpp -O3 -std=c++11 -o twentyseven
25:
	g++ twentyfive.cpp -O3 -std=c++11 -l sqlite3 -o twentyfive
clean:
	rm -f core.*
	rm -f vgcore.*
	rm -f twentyfive
	rm -f twentyseven
cldb:
	rm -f core.*
	rm -f vgcore.*
	rm -f *.db
	rm -f twentyfive
	rm -f twentyseven