7:
	g++ seven.cpp -std=c++11 -o seven
8:
	g++ eight.cpp -std=c++11 -o eight
9:
	javac nine.java
9_1:
	g++ nine_one.cpp -std=c++11 -o nineone
clean:
	rm -f seven
	rm -f eight
	rm -f nine
	rm -f nineone
	rm -f core.*
	rm -f vgcore.*
	rm -f *.class
