28: twentyeight.cpp
	g++ twentyeight.cpp -ggdb -std=c++11 -O3 -lpthread -o twentyeight
29: twentynine.cpp
	g++ twentynine.cpp -ggdb -std=c++11 -O3 -lpthread -o twentynine
clean:
	rm -f twentyeight
	rm -f twentynine
	rm -f core.*
	rm -f vgcore.*